### ISSUE TITLE
Discourse v2.2.0.beta8 prevents this plugin working

### ISSUE THREAD

**Issue by chriscroome** [muhlisbc/discourse-images-guardian#1]
The way in which icons are added to Discourse has changed and this means that this plugin is no longer working, see [this thread on meta.discourse.org](https://meta.discourse.org/t/upgrade-to-beta8-deletes-all-icons/106610/55), what would be involved to update this plugin so that it can be used again?

I have also [flagged this up on the plugin thread](https://meta.discourse.org/t/disallow-anonymous-users-from-viewing-image-file-urls/40335/22) on meta.discourse.org.

**Comment by muhlisbc** [comment]
@chriscroome 

Version 0.2.0 (eab74b6cf8c19bc080b6b0be2268623f9cf96528) provides custom settings that override the original setting. Not a fancy solution but it should be solid.

![deepinscreenshot_select-area_20190204235811](https://user-images.githubusercontent.com/26664997/52224232-16ae1600-28da-11e9-8e94-ba68bd2c4518.png)

![deepinscreenshot_select-area_20190204235658](https://user-images.githubusercontent.com/26664997/52224304-3e04e300-28da-11e9-9783-b548579773eb.png)

Let me know if it does fix the issue.

**Comment by chriscroome** [comment]
That seems to have done the job :slightly_smiling_face:

**Comment by muhlisbc** [comment]
Glad to hear that! I will close this issue. Feel free to reopen it if needed.

**Comment by chriscroome** [comment]
Is there a duplicate field, I can't work out the difference between:

> ## images guardian site home logo url
> *The logo image at the top left of your site. Use a wide rectangular image with a height of 120 and an aspect ratio greater than 3:1. If left blank, the site title text will be shown. (original setting: **logo**)*

And:

> ## images guardian site logo url
> *The logo image at the top left of your site. Use a wide rectangular image with a height of 120 and an aspect ratio greater than 3:1. If left blank, the site title text will be shown. (original setting: **logo**)*

**Comment by muhlisbc** [comment]
It's there for a reason. You can use the same value for both fields.

**Comment by chriscroome** [comment]
Great, thanks.
